### ISSUE TITLE
Automatic bootstrap download

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#795] opened 2019-08-30 14:06 UTC
It would be nice to be able to specify a bootstrap URL in the config file and have it automatically get downloaded on startup if the current bootstrap doesn't exist and there are no known nodes.

**Comment by majestrate** [comment] 2019-08-30 14:38
On Fri, Aug 30, 2019 at 07:06:48AM -0700, Jason Rhinelander wrote:
> It would be nice to be able to specify a bootstrap URL in the config file and have it automatically get downloaded on startup if the current bootstrap doesn't exist and there are no known nodes.
yeah but we'd need to link against libcurl which pulls in a metric shitload of stuff like x509 CA trust tomfoolery.
I had this as an external tool for this reason.

**Comment by neuroscr** [comment] 2019-09-05 00:37
seems like a duplicate of #80 and #491

**Comment by despair86** [comment] 2019-09-21 05:20
basically fixed with #825, all platforms now have their own magical incantation that launches some form of cURL for this

**Comment by despair86** [comment] 2019-09-21 05:36
dupe of #239

**Closed by despair86** 2019-09-21 05:36 UTC
Labels: bug
