### ISSUE TITLE
Occasional read dict failed in routing layer

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#364] opened 2019-02-28 07:42 UTC
Occurred on Windows 10  

> [WRN] (367) 02/28/19 18:38:23 AUS Eastern Summer Time path/path.cpp:623 Failed to parse inbound routing message
> [NFO] (367) 02/28/19 18:38:23 AUS Eastern Summer Time path/path.cpp:435 path TX=19c97ab91ee48620d8e12511b78a9b91 RX=f71cd7def0a4fa068b9202b4ad070a31 is building
> [ERR] (367) 02/28/19 18:38:23 AUS Eastern Summer Time routing/message_parser.cpp:140    read dict failed in routing layer

**Comment by majestrate** [comment] 2019-02-28 15:30
git revision plz

**Comment by KeeJef** [comment] 2019-03-05 04:44
Sorry, this is still present as of 

> lokinet-0.4.0-a4cd340f kuz yolo

Running on @despair86 's most recent windows debugging build, and an earlier non debugging build

**Comment by majestrate** [comment] 2019-03-18 12:41
this was caused by the path hop selection algorithm being borked and i believe this is fixed now.

**Closed by majestrate** 2019-03-18 12:41 UTC
Labels: question, staging
